#cloud-config
package_update: true
package_upgrade: true

packages:
  - htop
  - tar
  - git
  - wget
  - curl
  - nano
  - unzip
  - nvtop

write_files:
  - path: /etc/systemd/system/ollama.service.d/override.conf
    content: |
      [Service]
      Environment="OLLAMA_HOST=0.0.0.0"
      Environment="OLLAMA_FLASH_ATTENTION=1"

runcmd:
  - wget https://github.com/aristocratos/btop/releases/download/v1.4.0/btop-x86_64-linux-musl.tbz -O /tmp/btop.tbz
  - tar -xjvf /tmp/btop.tbz -C /tmp/btop
  - cd /tmp/btop && sudo make install
  # - curl -fsSL https://ollama.com/install.sh | sh
  # - ollama pull llama3.3
  # - systemctl daemon-reload
  # - systemctl restart ollama